import sqlite3
db=sqlite3.connect("Demo.db")
db.execute("Create table student(rollNo Integer Primary Key Autoincrement,name varchar(40),course varchar(30))")
db.execute("Create table courses(cid Integer Primary Key,cName varchar(40),duration integer not null)")
db.execute("Insert into student(name,course) values ('Aayush Sankhla','C++'),('Aditya Jain','Python'),('Anirav Sharma','Java')")
db.execute("Insert into courses values(1,'Python',6),(2,'Java',5),(3,'C++',2)")
db.execute("Create view stud_cour as Select s.rollNo,s.name,s.course,c.cid from student s join courses c on s.course=c.cName")
data=db.execute("select * from stud_cour")
rows=data.fetchall()
print(rows)
db.execute("update  student set name='Ankita' where rollNo=?",(2,))
db.execute("Delete from student where rollNo=2")
data=db.execute("select * from student")
rows=data.fetchall()
print(rows)
db.commit()
db.close()
